# MSc Artificial Intelligence Python Primer
# Unit 6 Jupyter Notebook 
# Introduction to NumPy


## Goals
This notebook has been created to familiarise you with the NumPy package. Most of the code needed to progress through this Notebook has been provided for you. However, there are several coding tasks that you will need to complete yourself by entering code yourself.

The topics in this notebook include:
* Creating NumPy Arrays
* Array Indexing and Slicing
* Array Reshaping
* Array Concatenation and Splitting
* Aggregations
* Comparisons and Masks
* Sorting

# Introduction to NumPy

Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science. In this notebook we will look at the specialized tools that Python has for handling such numerical arrays: the NumPy package. In the next unit, we will foicus on the Pandas package to provide even more techniques for effectively loading, storing, and manipulating in-memory data in Python.

NumPy (short for *Numerical Python*) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python's built-in ``list`` type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

The NumPy package is available in the Anaconda installation and so you simply need to import the package to access its tools and capabilities. By convention, you'll find that most people in the data science world will import NumPy using ``np`` as an alias.

In [ ]:
import numpy as np

## What is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array `dtype`. An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

## Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in ``array`` module can be used to create dense arrays of a uniform type:

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

Here ``'i'`` is a type code indicating the contents are integers. (more information about arrays can be found at https://docs.python.org/3/library/array.html).

Much more useful, however, is the ``ndarray`` object of the NumPy package. While Python's ``array`` object provides efficient storage of array-based data, NumPy adds to this efficient *operations* on that data.

## Creating Arrays from Python Lists

First, we can use ``np.array`` to create arrays from Python lists:

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type.
If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [ ]:
np.array([3.14, 4, 2, 3])

If we want to explicitly set the data type of the resulting array, we can use the ``dtype`` keyword:

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

The inner lists are treated as rows of the resulting two-dimensional array.

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.
Here are several examples:

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string (e.g. `np.zeros(10, dtype='int16')`) or using the associated NumPy object (e.g. `np.zeros(10, dtype=np.int16)`):

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

### <font color='red'><u>Worksheet Exercises</u></font>
1. Create a one-dimensional NumPy array with 100 32-bit unsigned integers all initialised to zero
2. Create a one-dimensional NumPy array with the even numbers between 1 and 20 in reverse order, e.g. 20, 18, 16, 14,...
3. Create a one-dimensional NumPy array with 12 evenly spaced between 1 and 100
4. Create a two-dimensional NumPy array with 5 rows and 2 columns of double precision float values all initialised to 1
5. Create a one-dimensional NumPy array with 10 random numbers generated from a normal distribution with a mean 100 and standard deviation 15
6. Create a three-dimensional NumPy array with 3x3x3 elements each initialised with the value 10
7. Create a two dimensional NumPy array with 2x3 8-bit byte values using the following given values (hint: use a List or Tuple):
```
1 6
2 5
4 3
```

In [ ]:
import numpy as np

# 1.
arr = np.zeros(100,dtype='int32')
print(arr)

print("-------------------------------------------------")

# 2.
arr = np.arange(20, 1, -2)
print(arr)

print("-------------------------------------------------")

# 3.
arr = np.linspace(1, 100, 12)
print(arr)

print("-------------------------------------------------")

# 4.
arr = np.ones((5, 2), dtype='float64')
print(arr)

print("-------------------------------------------------")

# 5.
arr = np.random.normal(100, 15, 10)
print(arr)

print("-------------------------------------------------")

# 6.
arr = np.full((3,3,3), 10)
print(arr)

print("-------------------------------------------------")

# 7.
arr = np.array([[1, 6],[2,5],[4,3]], dtype='int8')
print(arr)

print("-------------------------------------------------")

# Basics NumPy Operations

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), ``size`` (the total size of the array),  ``dtype`` (the data type of the array), ``itemsize`` (the size (in bytes) of each array element), and ``nbytes`` (the total size (in bytes) of the array):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

## Array Indexing: Accessing Single Elements

In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
print(x1) # all elements
print(x1[0]) # 1st value
print(x1[4]) # 5th value

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1] # the last element

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
print(x2)
print(x2[0,0]) # top left corner
print(x2[-1, -1]) # bottom right corner

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
print(x2)

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
x1[0] = 3.14159  # this will be truncated, i.e. it loses the .14159 decimal part!
print(x1)

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character. The NumPy slicing syntax follows the same syntax used for Python `List` and `string`. To access a slice of an array ``x``, use `x[start:stop:step]`. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10) # arange() is NumPy's version of range()
x

In [ ]:
x[:5]  # first five elements

In [ ]:
x[5:]  # elements after index 5

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x2

In [ ]:
x2[:2, :3]  # two rows, three columns

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
print(x2[:, 0])  # first column of x2

In [ ]:
print(x2[0, :])  # first row of x2

### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [ ]:
print(x2)

Let's extract a $2 \times 2$ subarray from this:

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

In [ ]:
print(x2)

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

In [ ]:
print(x2)

## Advanced Indexing
We can also pass arrays of indices in place of single scalars to access multiple array elements at once. This allows us to very quickly access and modify complicated subsets of an array's values. For example, consider the following array:

In [ ]:
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

### Accessing Values
Suppose we want to access three different elements. We could do it like this:

In [ ]:
[x[3], x[7], x[2]]

Alternatively, we can pass a single list or array of indices to obtain the same result:

In [ ]:
ind = [3, 7, 4]
x[ind]

We can also have control over the shape of the result. NOTE: it reflects the shape of the *index arrays* rather than the shape of the *array being indexed*:

In [ ]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

### Modifying Values
Just as we can use an array of indices to access parts of an array, we can also be use the same approach to modify parts of an array. For example, imagine we have an array of indices and we'd like to set the corresponding items in an array to some value:

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

We can use any assignment-type operator for this. For example:

In [ ]:
x[i] -= 10
print(x)

### <font color='red'><u>Worksheet Exercises</u></font>
1. Output the total size (in bytes) of the following NumPy array: `np.full((3, 5), 3.14)`
2. Output the type of data used for values stored in the NumPy array created in 1. above
3. Create a one-dimensional array with the numbers 1 to 10. Now, print the last element using a negative index.
4. Using the array created in 3., change the 4th element to -1
5. Using advanced indexing on the array created in 3. to also change the 2nd, 7th and 8th elements to -1
6. Create a two-dimensional array of 5x5 32-bit unsigned integers and initialise it to zero. Using array slicing, update the array to match the following:
```
0 0 0 0 0
0 1 1 1 0
0 1 1 1 0
0 1 1 1 0
0 0 0 0 0
```

In [ ]:
import numpy as np

# 1.
arr = np.full((3, 5), 3.14)
print(arr.nbytes)

print("-------------------------------------------------")

# 2.
print(arr.dtype)

print("-------------------------------------------------")

# 3.
arr = np.arange(1,11)
print(arr[-1])

print("-------------------------------------------------")

# 4.
arr[3] = -1
print(arr)

print("-------------------------------------------------")

# 5.
idxs = [1,6,7]
arr[idxs] = -1
print(arr)

print("-------------------------------------------------")

# 6.
arr = np.zeros((5,5),dtype='uint32')
arr[1:4,1:4] = 1
print(arr)

print("-------------------------------------------------")

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the ``reshape`` method will use a no-copy view of the initial array.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.

``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

It can also be used for two-dimensional arrays:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

### <font color='red'><u>Worksheet Exercises</u></font>
1. Create a one-dimensional NumPy array of 64 numbers ranging from 1 to 64. Now reshape this array into a grid of 8 x 8 elements.
2. Create two one-dimensional NumPy arrays of 8 alternating 0s and 1s. The first array should begin with a 1; the second array with a 0, i.e. 10101010 and 01010101. Now, use the `concatenate()` and `reshape()` functions to build a checkerboard of 8 x 8 elements
3. Given the following grid of 25 values, extract the 3 x 3 sub-grid of 9s from the larger grid using the `split()` function:
```
1 2 3 4 5
1 9 9 9 5
1 9 9 9 5
1 9 9 9 5
1 2 3 4 5
```

In [1]:
import numpy as np

# 1.
grid = np.arange(1,65).reshape((8, 8))
print(grid)

print("-------------------------------------------------")

# 2.
arr1 = np.zeros(8)
arr1[::2] = 1
arr2 = np.zeros(8)
arr2[1::2] = 1
checkerboard = np.concatenate([arr1,arr2,arr1,arr2,arr1,arr2,arr1,arr2])
checkerboard = checkerboard.reshape(8,8)
print(checkerboard)

print("-------------------------------------------------")

# 3.
x = np.array([[1, 2, 3, 4, 5],
     [1, 9, 9, 9, 5],
     [1, 9, 9, 9, 5],
     [1, 9, 9, 9, 5],
     [1, 2, 3, 4, 5]])
x1, x2, x3 = np.split(x, [1, 4])
y1, y2, y3 = np.split(x2, [1, 4], axis = 1)
print(y2)

print("-------------------------------------------------")

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
-------------------------------------------------
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
-------------------------------------------------
[[9 9 9]
 [9 9 9]
 [9 9 9]]
-------------------------------------------------


# Aggregations

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question.
Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.). NumPy has fast built-in aggregation functions for working on arrays.

## Summing the Values in an Array

As a quick example, consider computing the sum of all values in an array.
Python itself can do this using the built-in ``sum`` function:

In [ ]:
import numpy as np

In [ ]:
L = np.random.random(100)
sum(L)

The syntax is quite similar to that of NumPy's ``sum`` function, and the result is the same in the simplest case:

In [ ]:
np.sum(L)

However, because it executes the operation in compiled code, NumPy's version of the operation is computed much more quickly:

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

Be careful, though: the ``sum`` function and the ``np.sum`` function are not identical, which can sometimes lead to confusion!
In particular, their optional arguments have different meanings, and ``np.sum`` is aware of multiple array dimensions, as we will see in the following section.

## Minimum and Maximum

Similarly, Python has built-in ``min`` and ``max`` functions, used to find the minimum value and maximum value of any given array:

In [ ]:
min(big_array), max(big_array)

NumPy's corresponding functions have similar syntax, and again operate much more quickly:

In [ ]:
np.min(big_array), np.max(big_array)

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [ ]:
print(big_array.min(), big_array.max(), big_array.sum())

Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!

### Multi dimensional aggregates

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array:

In [ ]:
M = np.random.random((3, 4))
print(M)

By default, each NumPy aggregation function will return the aggregate over the entire array:

In [ ]:
M.sum()

Aggregation functions take an additional argument specifying the *axis* along which the aggregate is computed. For example, we can find the minimum value within each column by specifying ``axis=0``:

In [ ]:
M.min(axis=0)

The function returns four values, corresponding to the four columns of numbers.

Similarly, we can find the maximum value within each row:

In [ ]:
M.max(axis=1)

The way the axis is specified here can be confusing to users coming from other languages.
The ``axis`` keyword specifies the *dimension of the array that will be collapsed*, rather than the dimension that will be returned.
So specifying ``axis=0`` means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

### Other aggregation functions

NumPy provides many other aggregation functions. Additionally, most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point ``NaN`` value. The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

### <font color='red'><u>Worksheet Exercises</u></font>
1. Generate a one-dimensional NumPy array of 100000 random numbers using a normal distribution with mean 0 and standard deviation 1 (use the `random.normal()` function). Use aggregate functions to show mean and standard deviation of the array values and confirm that the normal random number generator approximates the given input parameters.
2. Using the array created in 1. above, find the following values using aggregate functions:
    * min and max values
    * the 25th percentile
    * the 50th percentile
    * the 75th percentile
3. Given the 5 x 5 magic square below, confirm that all rows, columns and diagonals sum to 65. NOTE: you may find the `sum()`, `diagonal()` and `fliplr()` functions useful for this exercise.
```
17 24 1 8 15
23 5 7 14 16
4 6 13 20 22
10 12 19 21 3
11 18 25 2 9
```

In [ ]:
import numpy as np

# 1.
from numpy import random
vals = random.normal(0,1,100000)
print("Mean = ", np.mean(vals))
print("Standard Deviation = ", np.std(vals))

print("-------------------------------------------------")

# 2.
print("Min = ", np.min(vals))
print("Max = ", np.max(vals))
print("25th Percentile = ", np.percentile(vals, 25))
print("50th Percentile = ", np.percentile(vals, 50))
print("75th Percentile = ", np.percentile(vals, 75))

print("-------------------------------------------------")

# 3.
magic = np.array([[17,24,1,8,15],
                 [23,5,7,14,16],
                 [4,6,13,20,22],
                 [10,12,19,21,3],
                 [11,18,25,2,9]])
print("Rows sums are ", np.sum(magic,axis=1))
print("Column sums are ", np.sum(magic,axis=0))
print("Left-to-right Diagonal sum is ", np.sum(np.diagonal(magic)))
print("Right-to-left Diagonal sum is ", np.sum(np.diagonal(np.fliplr(magic))))

print("-------------------------------------------------")

# Comparisons, Masks, and Boolean Logic

This section covers the use of Boolean masks to examine and manipulate values within NumPy arrays.
Masking comes up when you want to extract, modify, count, or otherwise manipulate values in an array based on some criterion: for example, you might wish to count all values greater than a certain value, or perhaps remove all outliers that are above some threshold.
In NumPy, Boolean masking is often the most efficient way to accomplish these types of tasks.

## Comparison Operators
NumPy has comparison operators (such as ``<`` (less than) and ``>`` (greater than)) that act in an element-wise way, i.e. per element of the NumPy array. The result of these comparison operators is always an array with a Boolean data type. All six of the standard comparison operations are available:

In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
x < 3  # less than

In [ ]:
x > 3  # greater than

In [ ]:
x <= 3  # less than or equal

In [ ]:
x >= 3  # greater than or equal

In [ ]:
x != 3  # not equal

In [ ]:
x == 3  # equal

These comparison operators will work on arrays of any size and shape. Here is a two-dimensional example:

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

In [ ]:
x < 6

In each case, the result is a Boolean array, and NumPy provides a number of straightforward patterns for working with these Boolean results.

## Working with Boolean Arrays

Given a Boolean array, there are a host of useful operations you can do.
We'll work with ``x``, the two-dimensional array we created earlier.

In [ ]:
print(x)

### Counting entries

To count the number of ``True`` entries in a Boolean array, ``np.count_nonzero`` is useful:

In [ ]:
# how many values less than 6?
np.count_nonzero(x < 6)

We see that there are eight array entries that are less than 6.
Another way to get at this information is to use ``np.sum``; in this case, ``False`` is interpreted as ``0``, and ``True`` is interpreted as ``1``:

In [ ]:
np.sum(x < 6)

The benefit of ``sum()`` is that like with other NumPy aggregation functions, this summation can be done along rows or columns as well:

In [ ]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

This counts the number of values less than 6 in each row of the matrix.

### Boolean operators

As with the comparison operators, Python's *bitwise logic operators*, ``&``, ``|``, ``^``, and ``~``work act in an element-wise way on (usually Boolean) arrays. Combining comparison operators and Boolean operators on arrays can lead to a wide range of efficient logical operations. For example, we can address this sort of compound question as follows:

In [ ]:
print(x)
np.sum((x >= 3) & (x <= 5)) # find the number of values between 3 and 5 inclusive

So we see that there are 6 numbers between 3 and 5 inclusive.

## Boolean Arrays as Masks

In the preceding section we looked at aggregates computed directly on Boolean arrays.
A more powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves.
Returning to our ``x`` array from before, suppose we want an array of all values in the array that are less than, say, 5:

In [ ]:
x

We can obtain a Boolean array for this condition easily, as we've already seen:

In [ ]:
x < 5

Now to *select* these values from the array, we can simply index on this Boolean array; this is known as a *masking* operation:

In [ ]:
x[x < 5]

What is returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the values in positions at which the mask array is ``True``. We are then free to operate on these values as we wish.

By combining Boolean operations, masking operations, and aggregates, we can very quickly answer these sorts of questions for our dataset.

### <font color='red'><u>Worksheet Exercises</u></font>
1. Imagine you want to simulate dice rolls. Use `randint()` to generate 100 dice rolls. Now, count the number of dice rolls greater than 3. 
2. Using the `loadtext()` function, read in the data stored in the file `1969 Birth Weights.csv` into a NumPy array. Now, count the number of babies who weigh between 4000g and 4500g
3. Using the same data as in 2. above, create a NumPy array containing all of the weights between 4000g and 4500g.

In [ ]:
# add your exercise solutions here
import numpy as np

# 1.
dice_rolls = np.random.randint(1,7,size=100)
print(np.count_nonzero(dice_rolls > 3))

print("-------------------------------------------------")

# 2.
weights = np.loadtxt('data/1969 Birth Weights.csv')
print(np.count_nonzero((weights >= 4000) & (weights <= 4500)))

print("-------------------------------------------------")

# 3.
weights_between_4000_4500 = weights[(weights >= 4000) & (weights <= 4500)]
print(weights_between_4000_4500)

print("-------------------------------------------------")

# Sorting Arrays

Up to this point we have been concerned mainly with tools to access and operate on array data with NumPy. This section covers algorithms related to sorting values in NumPy arrays. Although Python has built-in ``sort`` and ``sorted`` functions to work with Lists, here we will focus NumPy's ``np.sort`` and `np.argsort` functions which are much more efficient and useful.

The built-in `sort()` function sorts the array in-place, i.e. the array's values are changed. 

In [ ]:
x = np.array([2, 1, 4, 3, 5])
x.sort()
print(x)

To return a sorted version of the array without modifying the array, you can use `np.sort()`:

In [ ]:
x = np.array([2, 1, 4, 3, 5])
y = np.sort(x)
print(x,y) # original array unchanged

A related function is ``argsort``, which instead returns the *indices* of the sorted elements:

In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

The first element of this result gives the index of the smallest element, the second value gives the index of the second smallest, and so on. These indices can then be used to construct the sorted array if desired:

In [ ]:
x[i]

### Sorting along rows or columns

A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the ``axis`` argument. For example:

In [ ]:
rand = np.random.RandomState(42)
X = rand.randint(0, 20, (4, 6))
print(X)

In [ ]:
# sort each column of X
np.sort(X, axis=0)

In [ ]:
# sort each row of X
np.sort(X, axis=1)